language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || true; fi
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
